rings:
  - distance: 50
    height: 20
    rotation: 90
  - distance: 100
    height: 30
    rotation: 180
  - distance: 150
    height: 40
    rotation: 270
  - distance: 0
    height: 40
    rotation: 20
